### ISSUE TITLE
Achievement Tracker

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/Flood#35]
## Similar to TF2

Concept:
https://i.gyazo.com/4105359f95376bf660711d2efc2164b5.jpg
- [ ] Once right clicking on an achievement, it brings up a menu that will allow you to track. Also there should be an option to 'untrack' the achievement as well if it is on the tracking list.
- [ ] Achievements that are already completed cannot be tracked.
- [ ] Once achievement has been complete. That achievement will be removed from the tracking list.
- [ ] The amount of achievements that can be tracked is 3 to prevent clutters.

I know people can track their achievement by going onto their profile but it is a pain to do that.

**Comment by Donkie** [comment]
:+1:
